---
- name: Allow web traffic from the firewall
  ufw:
    rule: allow
    port: "{{ ufw_allow_port }}"
    proto:  tcp

- name: Allow ssh traffic from the firewall
  ufw:
    rule: allow
    port: "25"
    proto:  tcp

- name: Enable ufw
  ufw:
    state: enabled